name: set context
on: [pull_request, issues]
jobs:
  evaluate-expressions:
    runs-on: ubuntu-latest
    steps:
      - name: Display Contexts
        run: |
          echo '${{ toJson(github) }}'

          