name: Runname
on: [push, workflow_dispatch]
run-name: "WF event ${{ github.event_name}}Triggered by @${{ github.actor }} "
jobs:
  evaluate-expressions:
    runs-on: ubuntu-latest
    steps:
      - name: Display Contexts
        run: |
          echo '${{ toJson(runner) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          