name: Run conditions on steps
on: [push, pull_request]
jobs:
  run-during-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Run only during push
        run: echo "run only during push event"