name: set context
on: [push, workflow_dispatch]
jobs:
  evaluate-expressions:
    runs-on: ubuntu-latest
    steps:
      - name: Display Contexts
        run: |
          echo '${{ toJson(runner) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          